### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by tranduyhung** [arshad/crepido#5]
I get this error when running `gulp`

```
$ gulp
[11:55:50] Using gulpfile /var/www/html/crepido/gulpfile.js
[11:55:50] Starting 'sass'...
[11:55:50] Starting 'js'...
[11:55:50] Starting 'static'...
[11:55:50] Starting 'build'...
[11:55:50] Finished 'build' after 1.17 ms
[11:55:50] Starting 'webserver'...
[11:55:50] Webserver started at http://localhost:8000
[11:55:50] Finished 'webserver' after 5.96 ms
[11:55:50] Starting 'watch'...
[11:55:50] Finished 'watch' after 11 ms
[11:55:50] Finished 'static' after 26 ms
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1361:14)
    at listenInCluster (net.js:1402:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)
```

Here is package.json:

```
{
  "name": "Crepido",
  "version": "1.0.0",
  "description": "Create (kanban) boards to track users and projects from flat markdown files.",
  "main": "index.js",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "tracker",
    "tasklist",
    "projects"
  ],
  "author": "Arshad Chummun <arshad@chummun.com> (http://arshad.io/)",
  "repository": {
    "type": "git",
    "url": "arshad/crepido"
  },
  "license": "MIT",
  "dependencies": {
    "gulp": "~3.9.1",
    "gulp-data": "~1.3.1",
    "marked": "~0.3.17",
    "front-matter": "~2.3.0",
    "gulp-swig": "~0.8.0",
    "gulp-webserver": "~0.9.0",
    "gulp-sass": "~3.1.0",
    "gulp-concat": "~2.6.1",
    "gulp-uglify": "~3.0.0",
    "gulp-gh-pages": "~0.5.1"
  }
}
```

**Comment by Tsukreya** [comment]
It seems your port 8000 is in use, try changing the port in gulpfile.js like so:
```
gulp.task('webserver', function() {
  gulp.src('public')
    .pipe(webserver({
      livereload: true,
      open: true,
      port: 8921
    }));
});

```

**Comment by almereyda** [comment]
This error

```
Error: listen EADDRINUSE 127.0.0.1:8000
```

means you had another process running on port 8000 when trying this out.
